name: teego
description: Live Streaming app

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Default
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3

  #Images
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  image_cropper: ^4.0.1
  blur: ^3.1.0
  video_editor: ^3.0.0
  wechat_assets_picker: ^8.4.0
  wechat_camera_picker: ^3.7.0
  flutter_image_compress: ^2.0.4
  video_player: ^2.6.1
  mime: ^1.0.4
  preload_page_view: ^0.2.0
  like_button: ^2.0.5
  loading_animation_widget: ^1.2.0+4
  sliding_clipped_nav_bar: ^3.1.0+4
  path_provider: ^2.1.0

  #Backend
  parse_server_sdk_flutter: ^6.0.0

  #State management
  provider: ^6.0.5

  #Utilities
  easy_localization: ^3.0.1
  flutter_native_splash: ^2.2.19
  webview_flutter: ^4.0.6
  url_launcher: ^6.1.10
  universal_platform: ^1.0.0+1
  devicelocale: ^0.6.0
  shared_preferences: ^2.0.18
  url_strategy: ^0.2.0
  permission_handler: ^10.2.0
  share_plus: ^7.1.0
  stop_watch_timer: ^3.0.1
  flutter_windowmanager: ^0.2.0
  fade_shimmer: ^2.2.0
  sticky_grouped_list: ^3.1.0
  visibility_detector: ^0.4.0+2

  iban: ^1.0.1
  # wakelock: ^0.6.2
  whatsapp_unilink: ^2.1.0
  keyboard_attachable: ^2.1.0
  just_audio: ^0.9.31
  helpers: ^1.2.0
  upgrader: ^6.0.1 #Dont upgrade it for Parse Server package
  flutter_staggered_grid_view: ^0.7.0

  #Calls and live streaming
  agora_rtc_engine: ^6.2.2 #Dont upgrade it

  agora_rtm: ^1.5.0
  flutter_ringtone_player: ^3.2.0
  flutter_callkit_incoming: ^2.0.0+1
  flutter_screenutil: '>=5.5.3+2 <5.6.1'
  zego_uikit: ^2.12.0
  zego_uikit_prebuilt_live_streaming: ^2.18.1
  zego_uikit_signaling_plugin: ^2.5.0

  #Geo data and phone helper
  #  country_provider: ^1.0.2
  intl_phone_number_input: ^0.7.2
  pin_code_fields: ^8.0.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  location: ^5.0.2+1
  #Animations and icons
  lottie: ^2.3.0

  #Firebase
  firebase_core: ^2.7.1
  firebase_messaging: ^14.2.6
  firebase_analytics: ^10.1.5
  #  firebase_performance: ^0.9.0+15
  firebase_crashlytics: ^3.0.16
  firebase_dynamic_links: ^5.0.16

  #push notifications
  another_flushbar: ^1.12.29

  #Social login
  firebase_auth: ^4.2.10
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^5.0.8

  #payments:
  purchases_flutter: ^5.6.0

  # fake name
  faker: ^2.1.0

  #Ads
  # google_mobile_ads: ^3.0.0
  app_tracking_transparency: ^2.0.3

  #Libraries
  xml: ^6.2.2
  flutter_linkify: ^6.0.0
  marquee: ^2.2.3
  # hashtagable: ^2.1.0
  http:
  google_mobile_ads: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/svg/
    - assets/audio/

dependency_overrides:
  # parse_server_sdk: ^5.1.3
  package_info_plus: ^3.0.3
  camera_android: ^0.10.4+3
  #dio: ^5.0.2

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/splash.png
  #branding: assets/branding-production.png
  color_dark: '#000000'
  image_dark: assets/images/ic_logo_white.png
  #branding_dark: assets/branding-production.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: '#ffffff'
    image_dark: assets/images/ic_logo_white.png
    icon_background_color_dark: '#000000'

  web: false
